---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: crdb-go-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crdb-go-quickstart
  template:
    metadata:
      labels:
        app: crdb-go-quickstart
        deploymentconfig: crdb-go-quickstart
    spec:
      containers:
        - name: crdb-go-quickstart
          image: quay.io/myeung/crdb-go-quickstart:v0.0.1
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: crdb-go-quickstart
  name: crdb-go-quickstart
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: crdb-go-quickstart
    deploymentconfig: crdb-go-quickstart
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: crdb-go-quickstart
  name: crdb-go-quickstart
spec:
  to:
    kind: Service
    name: crdb-go-quickstart
